### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by VictoryLN** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#11]
what the red dots mean? Do they mean the sample locations?
When visualize conv4, the conv3 is a vanilla convolution, so it is reasonable use resize function to calculate output_conv3's the reception field. But when visualize conv5, the conv4 is a deformable convolution. Is it something wrong with conv5?
Do I get wrong?

**Comment by developer0hye** [comment]
@VictoryLN 
Yes, red dots mean the sampling locations for green dot. 

In the paper, they visualized sampling locations about several deformable convolution layers. I just followed them.

Becuase deformable convolution layer's dynamic offset is predicted on downsampled feature map, I resized them.
 
There is no something wrong with conv5.

**Comment by VictoryLN** [comment]
Fine, thanks for reply.
