### ISSUE TITLE
Visualization for deeper layers

### ISSUE THREAD

**Issue by vkothapally** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#13]
Hi, thank you for your precise code for deformable convolutions. I was wondering if you would be able to help implement visualization for the multi-layer Deformable CNNs. The current visualization code you have has only one layer of deformable
CNN, does the current visualization script work if all
The layers are replaced with deformable CNNs?

**Comment by developer0hye** [comment]
Hi, Vinay

My implmentation visualizes the multi-layer Deformable CNNs. My current visualization code has two layers of deformable CNN. I expect that it will work after replacing all convolutional layers with deformable convolutional layers.
