### ISSUE TITLE
感觉您写的可视化有问题

### ISSUE THREAD

**Issue by LYMDLUT** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#17]
offsets_y = offsets[:, :9]
        offsets_x = offsets[:, 9:]
应该为：
        offsets_y = offsets[:, ::2]
        offsets_x = offsets[:, 1::2]

**Comment by developer0hye** [comment]
@LYMDLUT What makes you think so?

**Comment by LYMDLUT** [comment]
https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/blob/7e69911acfca4183172b829c50b174af721310e8/src/deform_conv_cuda_kernel.cu#L207-L228

**Comment by developer0hye** [comment]
@LYMDLUT 

I will check it. Thanks!

**Comment by developer0hye** [comment]
@LYMDLUT 
Thanks! It was my huge mistake.
