### ISSUE TITLE
DCNV2 MODULATOR WEIGHT

### ISSUE THREAD

**Issue by zhenyuzhouiu** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#18]
https://github.com/developer0hye/PyTorch-Deformable-Convolution-v2/blob/4d958ebbaa6fc7aab3a6d06396181d929e1db7fa/dcn.py#L54

I have a question about the modulator weight. Why do you use 2 to multiply the result of the sigmoid() instead of 1? Shouldn't this modulator range from 0 to 1?

![Screenshot from 2022-04-13 11-46-47](https://user-images.githubusercontent.com/29830605/163096306-9b8ecd77-0adc-4ee5-aa29-e07eb61e101b.png)

**Comment by developer0hye** [comment]
@zhenyuzhouiu 
Good question

I followed [the original implementation](https://github.com/msracver/Deformable-ConvNets/blob/6aeda878a95bcb55eadffbe125804e730574de8d/DCNv2_op/example_symbol.py#L6-L18), but I don't know why it is designed that way.

I also uploaded this issue to the official implementation project, but I couldn't get the answer.

https://github.com/msracver/Deformable-ConvNets/issues/280

I got improved results by multiplying 2 by a modulator.
