### ISSUE TITLE
How to cite 'PyTorch-Deformable-Convolution-v2'?

### ISSUE THREAD

**Issue by DezzardHD** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#19]
Hey,

I've used your implementation in a work of mine.
Now I want to give credit to you. Unfortunately I don't know how to cite this repository.
GitHub has a [feature](https://github.blog/2021-08-19-enhanced-support-citations-github/) that allows you to define how someone should cite your repository.

You might consider using that feature. :) 

Best regards
DezzardHD

**Comment by developer0hye** [comment]
Hi @DezzardHD,

I added citation.cff file for your citation, please check it.

Thanks!

Best regards
Yonghye

**Comment by DezzardHD** [comment]
Hi @developer0hye ,
thank you very much! :)

Best regards
DezzardHD
