### ISSUE TITLE
NaN values in offset

### ISSUE THREAD

**Issue by toannguyen1904** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#20]
In my model, the offset values get super big and small, so they end up with NaN values. Because of this, my network does not work. How can I fix it? I see you use the clamp() function to limit offset values. But it is useless in this case.

**Comment by developer0hye** [comment]
I think that dcn may be a not optimal operation in your case.

Try using sigmoid function to limit the range of offset values with small scale value `a`.
```
offset = a * torch.sigmoid(self.offset_conv(x))
```

**Comment by toannguyen1904** [comment]
Thank you so much, it works now. But I have one more question. What is the usual range of the offset values?

**Comment by developer0hye** [comment]
@toannguyen1904 

I think it should not be greater than the size of the feature map.
It is hard to extrapolate values out of the feature map.
