### ISSUE TITLE
Why initialize the parameters to zero?

### ISSUE THREAD

**Issue by huiwong96** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#21]
THANKS FOR YOUR CODE.
I noticed the code init the offset conv parameters to zeros，why？

**Comment by developer0hye** [comment]
Hi, @huiwong96

Reading a [paper](
https://openaccess.thecvf.com/content_ICCV_2017/papers/Dai_Deformable_Convolutional_Networks_ICCV_2017_paper.pdf
) is all you need.

I guess authors may wanted for deformable convolution to be worked like a regular convolution in early training steps. 

![image](https://user-images.githubusercontent.com/35001605/190887785-522fd198-e36d-46f7-a3cb-0316383f8f07.png)
