### ISSUE TITLE
how to calculate flops of deformable convolution

### ISSUE THREAD

**Issue by kepengxu** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#22]
how to calculate flops of deformable convolution
thank you!

**Comment by developer0hye** [comment]
@kepengxu 

The deformable convolution is **mainly** composed of **three convolutional layers**.

K: number of kernel parameters
M:  size of feature map 
C_in: input feature map channel size
C_out:  output feature map channel size

FLOPs(Deformable Convolution) = 3 x (((K x M + (K - 1) x M) x C_in x C_out) +  (C_in -1) x C_out)

K x M (The number of multiplication for 2d convolution)

(K-1) x M (The number of addition for 2d convolution)

(C_in -1) x C_out) (The number of addition to sum each channel's value after 2d convolution)

I didn't consider the FLOPs for bilinear interpolation and modulator.
