### ISSUE TITLE
Reproducability/Setting seed

### ISSUE THREAD

**Issue by RGring** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#25]
Hi,
Thanks for your code.
The issue is not directly related to your code, but the torchvision.ops.deform_conv2d - function, that is wrapped.
I was wondering if it is possible to preserve reproducibility? When setting all the common torch/numpy/random seeds, I don't get same results when using torchvision.ops.deform_conv2d.

Thanks again!

**Comment by developer0hye** [comment]
@RGring Hi!
Is DCN the only one operator that has no reproducability in your model?
