### ISSUE TITLE
what's the meaning of   modulator = 2. * torch.sigmoid(self.modulator_conv(x))

### ISSUE THREAD

**Issue by hitbuyi** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#26]
in  dcn.py, function  forward(self, x):

`modulator = 2. * torch.sigmoid(self.modulator_conv(x))`

why  the result of sigmod is multiplied by 2, what's the meaning?

**Comment by developer0hye** [comment]
@hitbuyi 
Hi, I just followed [original implementation](https://github.com/apache/mxnet/blob/5722f8b38af58c5a296e46ca695bfaf7cff85040/python/mxnet/gluon/nn/conv_layers.py#L1613). I am also curious about it.
