### ISSUE TITLE
About clamping offsets

### ISSUE THREAD

**Issue by Agent-INF** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#6]
Thanks for your repo!
I'm curious about the line you commented out:
https://github.com/developer0hye/Simple-PyTorch-Deformable-Convolution-v2/blob/5578b559e497cc0fd0dc452f6dab9c421f1f8463/dcn.py#L50
Is clamping offsets necessary?  Will it stabilize the training?

**Comment by developer0hye** [comment]
@Agent-INF 
I expected it to stabilize the training. Actually I have not experimented about clamping deeply yet.

**Comment by Agent-INF** [comment]
Okay, thank you very much!
