### ISSUE TITLE
what is torch version for this dcn?

### ISSUE THREAD

**Issue by zgsxwsdxg** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#7]
firstly, thank for your good job. I use torch1.8.0 ,but torchvision.ops.deform_conv2d() function no parameter 'mask' , any solution for it?

**Comment by developer0hye** [comment]
Hi! Refer to #3.

**Comment by zgsxwsdxg** [comment]
> Hi! Refer to #3.

Thank you.  I also want to ask how to realize the module ModulatedDeformConv and ModulatedDeformConvPack on your code for paper DCNv2？ Please give me some guidance or Would you consider implementing this function？

**Comment by developer0hye** [comment]
Refer to #2.

Refer to 
https://github.com/pytorch/vision/blob/19ad0bbc5e26504a501b9be3f0345381d6ba1efc/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu#L208-L209

**Comment by developer0hye** [comment]
@zgsxwsdxg Did it help you solve your problem?

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg Did it help you solve your problem?

There are truly difficulties for me to implement the functions because I am too lack of familiarity to c++ and cuda procedure to understand the https://github.com/pytorch/vision/blob/19ad0bbc5e26504a501b9be3f0345381d6ba1efc/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu#L208-L209. 

Do you consider implementing it？ Looking forward to your solution. best wishes for you.

**Comment by developer0hye** [comment]
@zgsxwsdxg 

I don't consider implementing it. Actually, I am also lack of knowledge about CUDA programming.

Why do you want to implement DCNv2 from scratch instead of using pytorch's implementation?

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg
> 
> I don't consider implementing it. Actually, I am also lack of knowledge about CUDA programming.
> 
> Why do you want to implement DCNv2 from scratch instead of using pytorch's implementation?

Thx, pytorch doesn’t have ModulatedDeformConv and ModulatedDeformConvPack function，I perfer to python code for these code function. DCNv2 is c++ and cuda programming to need to be built for difficulty.

**Comment by developer0hye** [comment]
@zgsxwsdxg 

I think ModulatedDeformConv is the same as DCNv2. And my project is the implementation of DCNv2. What are you considering?

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg
> 
> I think ModulatedDeformConv is the same as DCNv2. And my project is the implementation of DCNv2. What are you considering?

Thanks.
